[project]
name = "moontransfer"
version = "0.1.0"
description = "Cross-platform GUI for secure file transfers via croc"
readme = "README.md"
requires-python = ">=3.13,<3.15"
dependencies = [
    "PySide6>=6.6",
]

[project.scripts]
moontransfer = "moontransfer.app:main"

[dependency-groups]
dev = [
    "pillow>=12.3.0",
    "pyinstaller>=6.0",
]

[tool.moontransfer.croc]
version = "11.0.1"

[tool.moontransfer.croc.hashes]
"croc_v11.0.1_Linux-64bit.tar.gz" = "sha256:6fd43efd19ac593412c8981484e2fdf8aae7f19ce43363beefcf77bae9dfcbd2"
"croc_v11.0.1_Linux-ARM64.tar.gz" = "sha256:1626c4a5ce73da171146e0f336ca40118c0a2b4b617421aa53f6addc54de6459"
"croc_v11.0.1_macOS-64bit.tar.gz" = "sha256:fd7e21b291c9ab32c9b1005d3fd00d0630a8c03385411432f563ec385e42a6e9"
"croc_v11.0.1_macOS-ARM64.tar.gz" = "sha256:b49e1e22dd690723cd31fb2876842db9b1ea4232150b980ae1fa46c8cc7f2467"
"croc_v11.0.1_Windows-64bit.zip" = "sha256:4399eabe6fed9be2c03bfaad3140e7b6d6b35067ac0768faa1d3129c653366a5"
"croc_v11.0.1_Windows-ARM64.zip" = "sha256:1a99f4d8b2a338f00bfa83f134c375454b52a14f6992b63523887252aa051c6f"

[build-system]
requires = ["uv_build>=0.10.0,<0.11.0"]
build-backend = "uv_build"
