[app]
title = MoonTransfer
package.name = moontransfer
package.domain = io.github.gaumeloth

# Generated by tools/prepare_android.py. Never edit files in this directory.
source.dir = ../build/android/source
source.include_exts = py,png,kv,json,txt
source.exclude_dirs = __pycache__

version.regex = (?m)^__version__ = ["']([^"']+)["']
version.filename = %(source.dir)s/main.py

# Kivy 2.3.1 officially supports Python through 3.13.
requirements = python3==3.13.14,hostpython3==3.13.14,kivy==2.3.1,chardet==5.2.0,croc

icon.filename = %(source.dir)s/moontransfer/assets/icons/moontransfer-icon.png
orientation = all
fullscreen = 0

# SAF will be used for user-selected files; broad storage permissions are
# deliberately omitted.
android.permissions = android.permission.INTERNET,
    android.permission.FOREGROUND_SERVICE,
    android.permission.FOREGROUND_SERVICE_DATA_SYNC,
    android.permission.POST_NOTIFICATIONS
services = Transfer:moontransfer_android/service.py:foreground:sticky:foregroundServiceType=dataSync
android.add_src = java
android.service_class_name = io.github.gaumeloth.moontransfer.MoonTransferPythonService
android.api = 36
android.minapi = 24
android.ndk = 28c
android.ndk_api = 24
android.archs = arm64-v8a
android.numeric_version = 1
android.allow_backup = False
android.enable_androidx = True
android.debug_artifact = apk
android.release_artifact = aab

p4a.branch = v2026.05.09
p4a.bootstrap = sdl2
p4a.local_recipes = recipes

[app@ci]
# CI runs without a terminal. Keep automatic SDK license acceptance explicit
# and isolated from local builds, which retain Buildozer's interactive prompt.
android.accept_sdk_license = True

[buildozer]
log_level = 2
warn_on_root = 1
build_dir = ../build/android/buildozer
bin_dir = ../dist/android
