from __future__ import annotations

import argparse
import shutil
import sys
import tempfile
import tomllib
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
if __package__ in {None, ""}:
    sys.path.insert(0, str(ROOT))

from tools.build_metadata import create_build_metadata, write_build_metadata

SHARED_MODULES = (
    "__init__.py",
    "build_info.py",
    "cancellation.py",
    "croc.py",
    "files.py",
    "messages.py",
    "payload.py",
    "progress.py",
    "protocol.py",
    "resources.py",
)
ANDROID_ASSET_SUFFIXES = frozenset({".png"})


def read_project_version(pyproject: Path) -> str:
    with pyproject.open("rb") as stream:
        data = tomllib.load(stream)

    version = data.get("project", {}).get("version")
    if not isinstance(version, str) or not version:
        raise RuntimeError("Missing project version in pyproject.toml.")
    return version


def _copy_android_app(source: Path, destination: Path) -> None:
    if not source.is_dir():
        raise RuntimeError(f"Android application sources not found: {source}")
    shutil.copytree(
        source,
        destination,
        dirs_exist_ok=True,
        ignore=shutil.ignore_patterns("__pycache__", "*.pyc"),
    )


def _copy_shared_package(source: Path, destination: Path) -> None:
    destination.mkdir(parents=True, exist_ok=True)
    for filename in SHARED_MODULES:
        source_file = source / filename
        if not source_file.is_file():
            raise RuntimeError(f"Shared Android module not found: {source_file}")
        shutil.copy2(source_file, destination / filename)

    assets_source = source / "assets"
    for asset in sorted(assets_source.rglob("*")):
        if not asset.is_file() or asset.suffix.lower() not in ANDROID_ASSET_SUFFIXES:
            continue
        relative_path = asset.relative_to(source)
        target = destination / relative_path
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(asset, target)


def _write_entrypoint(destination: Path, version: str) -> None:
    entrypoint = (
        "# Generated by tools/prepare_android.py.\n"
        f'__version__ = "{version}"\n\n'
        "from moontransfer_android.application import main\n\n\n"
        'if __name__ == "__main__":\n'
        "    main()\n"
    )
    (destination / "main.py").write_text(entrypoint, encoding="utf-8")


def prepare_android_source(
    *,
    root: Path = ROOT,
    destination: Path | None = None,
) -> Path:
    root = root.resolve()
    destination = (
        destination
        if destination is not None
        else root / "build" / "android" / "source"
    ).expanduser().absolute()
    if destination.is_symlink():
        raise RuntimeError(f"Refusing to replace a symbolic link: {destination}")
    if destination.exists() and not destination.is_dir():
        raise RuntimeError(f"Android build source is not a directory: {destination}")

    destination.parent.mkdir(parents=True, exist_ok=True)
    temporary = Path(
        tempfile.mkdtemp(prefix="moontransfer-android-", dir=destination.parent)
    )
    try:
        _copy_android_app(root / "android" / "app", temporary)
        _copy_shared_package(
            root / "src" / "moontransfer",
            temporary / "moontransfer",
        )
        version = read_project_version(root / "pyproject.toml")
        _write_entrypoint(temporary, version)
        write_build_metadata(
            temporary / "moontransfer" / "build-info.json",
            create_build_metadata(root),
        )

        if destination.exists():
            shutil.rmtree(destination)
        temporary.replace(destination)
    except BaseException:
        shutil.rmtree(temporary, ignore_errors=True)
        raise

    return destination


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Prepare the isolated source tree used by the Android prototype."
    )
    parser.add_argument(
        "--destination",
        type=Path,
        help="Override the generated source destination.",
    )
    args = parser.parse_args()

    destination = prepare_android_source(destination=args.destination)
    print(destination)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
